name: Docker-Security-Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  Docker_Security_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t SSH_APP:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'SSH_APP:latest'
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
